# Generated by Django 4.2 on 2023-11-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
