# Generated by Django 4.2 on 2023-12-08 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneytracker', '0002_asset_customuser_performance_portfolio_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('acquisition_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='suscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='days_to_send_email',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='performance',
            constraint=models.UniqueConstraint(fields=('user', 'days_to_send_email'), name='unique_performance'),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneytracker.asset'),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneytracker.portfolio'),
        ),
        migrations.RemoveField(
            model_name='performance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='total_portfolio_value',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='acquisition_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='quantity',
        ),
        migrations.AddConstraint(
            model_name='portfolioasset',
            constraint=models.UniqueConstraint(fields=('portfolio', 'asset'), name='unique_portfolio_asset'),
        ),
    ]
