# Generated by Django 4.2 on 2023-12-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneytracker', '0003_portfolioasset_alter_performance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='assets',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_users',
        ),
        migrations.AlterModelTable(
            name='performance',
            table='performances',
        ),
        migrations.AlterModelTable(
            name='portfolio',
            table='portfolios',
        ),
        migrations.AlterModelTable(
            name='portfolioasset',
            table='portfolios_asset',
        ),
    ]
