# Generated by Django 4.2 on 2023-12-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneytracker', '0004_alter_asset_table_alter_customuser_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolioasset',
            table='portfolios_assets',
        ),
    ]
