# Generated by Django 4.2 on 2024-01-05 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneytracker', '0006_assetprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAssetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('timestamp', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneytracker.asset')),
            ],
            options={
                'db_table': 'daily_asset_info',
            },
        ),
        migrations.DeleteModel(
            name='AssetPrice',
        ),
    ]
