# Generated by Django 4.2 on 2023-12-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneytracker', '0006_assetprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='asset',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
