# Generated by Django 4.2 on 2023-12-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneytracker', '0006_assetprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='volume',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
