# Generated by Django 4.2 on 2024-01-08 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneytracker', '0007_dailyassetinfo_delete_assetprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='last_time_sendend',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='performance',
            name='periodicity',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Biweekly', 'Biweekly')], default='Weekly'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='days_to_send_email',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday'),
        ),
    ]
