# Generated by Django 4.2 on 2024-01-13 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneytracker', '0009_rename_last_time_sendend_performance_last_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyassetinfo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
