# Generated by Django 4.2 on 2024-01-23 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneytracker', '0010_alter_dailyassetinfo_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioasset',
            name='acquisition_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18),
        ),
    ]
